name: Deploy to Windows Server

on:
  push:
    branches:
      - main  # Adjust branch name as per your setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: '13.235.132.136'
          username: 'Administrator'
          password: '5bg6tUy207U6lfYEgfozT9BQ4w)SzOq$'  # Hardcoded password
          port: 22
          timeout: '60s'
          command_timeout: '10m'
          debug: true  # To enable debugging and get detailed logs

      - name: Create directory on Windows Server
        run: |
          sshpass -p '5bg6tUy207U6lfYEgfozT9BQ4w)SzOq$' ssh -o StrictHostKeyChecking=no Administrator@13.235.132.136 "if not exist C:\\inetpub\\wwwroot mkdir C:\\inetpub\\wwwroot"

      - name: Deploy files to Windows Server
        run: |
          sshpass -p '5bg6tUy207U6lfYEgfozT9BQ4w)SzOq$' scp -o StrictHostKeyChecking=no -r ./* Administrator@13.235.132.136:C:/inetpub/wwwroot

      - name: Verify Deployment
        run: |
          sshpass -p '5bg6tUy207U6lfYEgfozT9BQ4w)SzOq$' ssh Administrator@13.235.132.136 " dir C:\\inetpub\\wwwroot"
