name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: '13.232.131.235'
          username: 'Administrator'
          password: '${{ secrets.SSH_PASSWORD }}'
          port: 22
          timeout: '60s'  # Extended timeout for the connection
          command_timeout: '10m'

      - name: Create directory on Windows Server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no Administrator@13.232.131.235 "if not exist C:\\inetpub\\wwwroot mkdir C:\\inetpub\\wwwroot"

      - name: Deploy files to Windows Server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./* Administrator@13.232.131.235:C:/inetpub/wwwroot

      - name: Verify Deployment
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh Administrator@13.232.131.235 "dir C:\\inetpub\\wwwroot"
